{
 "title": "Executive Overview",
 "time": { "from": "2016-01-01T03:00:00.000Z", "to": "2019-01-01T02:59:59.000Z" },
 "panels": [
  {
   "title": "Total Revenue",
   "type": "stat",
   "description": "Total revenue based on dashboard viewing timeframe. \"cancelled\" and \"unavailable\" orders are excluded.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sum(item_total_value) AS \"Total Revenue\"\r\nFROM brazilian_ecommerce.fact_order_items\r\nWHERE $__timeFilter(purchase_timestamp)\r\n  AND order_status NOT IN ('canceled', 'unavailable');"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "stat",
   "description": "Total orders based on dashboard viewing timeframe. \"cancelled\" and \"unavailable\" orders are excluded.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    uniqExact(order_id) AS \"Total Orders\"\r\nFROM brazilian_ecommerce.fact_order_items\r\nWHERE $__timeFilter(purchase_timestamp)\r\n  AND order_status NOT IN ('canceled', 'unavailable');"
    }
   ]
  },
  {
   "title": "Average Order Value (AOV)",
   "type": "stat",
   "description": "Calculates the AOV based on dashboard viewing timeframe. \"canceled\" and \"unavailable\" orders are excluded.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sum(item_total_value) / uniqExact(order_id) AS \"Avg Order Value\"\r\nFROM brazilian_ecommerce.fact_order_items\r\nWHERE $__timeFilter(purchase_timestamp)\r\n  AND order_status NOT IN ('canceled', 'unavailable');"
    }
   ]
  },
  {
   "title": "Active Customers",
   "type": "stat",
   "description": "Number of active customers based on accounts rather than transaction counts.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    uniqExact(c.customer_unique_id) AS \"Active Customers\"\r\nFROM brazilian_ecommerce.fact_order_items f\r\nJOIN brazilian_ecommerce.dim_customers c ON f.customer_key = c.customer_key\r\nWHERE $__timeFilter(f.purchase_timestamp)\r\n  AND f.order_status NOT IN ('canceled', 'unavailable');"
    }
   ]
  },
  {
   "title": "Total Items Sold",
   "type": "stat",
   "description": "Each order can have multiple items.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    count() AS \"Items Sold\"\r\nFROM brazilian_ecommerce.fact_order_items\r\nWHERE $__timeFilter(purchase_timestamp)\r\n  AND order_status NOT IN ('canceled', 'unavailable');"
    }
   ]
  },
  {
   "title": "Revenue Trend Over Time",
   "type": "timeseries",
   "description": "Excludes orders that are \"canceled\" or \"unavailable\".",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    $__timeInterval(purchase_timestamp) AS time,\r\n    sum(item_total_value) AS \"Total Revenue\",\r\n    sum(price) AS \"Product Revenue\",\r\n    sum(freight_value) AS \"Freight Value\"\r\nFROM brazilian_ecommerce.fact_order_items\r\nWHERE $__timeFilter(purchase_timestamp)\r\n  AND order_status NOT IN ('canceled', 'unavailable')\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Order Status Distribution",
   "type": "piechart",
   "description": "Shows how many unique orders in each order status.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    order_status AS \"Status\",\r\n    uniqExact(order_id) AS \"Orders\"\r\nFROM brazilian_ecommerce.fact_order_items\r\nWHERE $__timeFilter(purchase_timestamp)\r\nGROUP BY order_status\r\nORDER BY Orders DESC;"
    }
   ]
  },
  {
   "title": "Revenue by Product Category",
   "type": "barchart",
   "description": "Excluding \"canceled\" and \"unavailable\" orders",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    p.category_name AS \"Category\",\r\n    sum(f.item_total_value) AS \"Revenue\"\r\nFROM brazilian_ecommerce.fact_order_items f\r\nJOIN brazilian_ecommerce.dim_products p ON f.product_key = p.product_key\r\nWHERE $__timeFilter(f.purchase_timestamp)\r\n  AND f.order_status NOT IN ('canceled', 'unavailable')\r\n  AND p.category_name IS NOT NULL\r\nGROUP BY p.category_name\r\nORDER BY Revenue DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Sales by Day of Week",
   "type": "barchart",
   "description": "Excluding \"canceled\" and \"unavailable\" orders",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    d.day_of_week AS day_order,\r\n    d.day_name AS \"Day\",\r\n    sum(f.item_total_value) AS \"Revenue\"\r\nFROM brazilian_ecommerce.fact_order_items f\r\nJOIN brazilian_ecommerce.dim_dates d ON f.purchase_date_key = d.date_key\r\nWHERE $__timeFilter(f.purchase_timestamp)\r\n  AND f.order_status NOT IN ('canceled', 'unavailable')\r\nGROUP BY d.day_of_week, d.day_name\r\nORDER BY day_order;"
    }
   ]
  },
  {
   "title": "Revenue Distribution by State",
   "type": "table",
   "description": "Excludes \"canceled\" and \"unavailable\" orders.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    c.state AS \"State\",\r\n    uniqExact(f.order_id) AS \"Orders\",\r\n    sum(f.item_total_value) AS \"Revenue\",\r\n    sum(f.item_total_value) / uniqExact(f.order_id) AS \"Avg Order Value\",\r\n    uniqExact(c.customer_unique_id) AS \"Customers\"\r\nFROM brazilian_ecommerce.fact_order_items f\r\nJOIN brazilian_ecommerce.dim_customers c ON f.customer_key = c.customer_key\r\nWHERE $__timeFilter(f.purchase_timestamp)\r\n  AND f.order_status NOT IN ('canceled', 'unavailable')\r\nGROUP BY c.state\r\nORDER BY Revenue DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}