services:
  clickhouse:
    image: clickhouse:25.9
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface (for DbVisualizer or Python)
      - "9000:9000" # Native protocol interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    image: grafana/grafana:12.3.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  clickhouse_data:
  clickhouse_logs:
  grafana_storage: